# Generated by Django 5.0 on 2023-12-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0003_alter_employee_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('HR', 'Human Resources'), ('Marketing', 'Marketing'), ('CMS', 'CMS'), ('Finance', 'Finance')], max_length=20),
        ),
    ]
